import { AnalysisResult } from './types';

export function exportToJSON(result: AnalysisResult): void {
  const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
  downloadBlob(blob, `infengine-analysis-${Date.now()}.json`);
}

export function exportToMarkdown(result: AnalysisResult): void {
  const md = generateMarkdownReport(result);
  const blob = new Blob([md], { type: 'text/markdown' });
  downloadBlob(blob, `infengine-analysis-${Date.now()}.md`);
}

export function exportToExecutiveSummary(result: AnalysisResult): void {
  const summary = generateExecutiveSummary(result);
  const blob = new Blob([summary], { type: 'text/plain' });
  downloadBlob(blob, `infengine-executive-summary-${Date.now()}.txt`);
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function generateMarkdownReport(result: AnalysisResult): string {
  const lines: string[] = [
    `# INFENGINE Decision Analysis Report`,
    ``,
    `**Generated:** ${new Date(result.createdAt).toLocaleString()}`,
    ``,
    `## Decision`,
    `> ${result.decision}`,
    ``,
    `## Options Evaluated`,
    ...result.options.map((o) => `- **${o.name}**: ${o.description || ''}`),
    ``,
    `---`,
    ``,
    `## 🏆 Recommendation`,
    ``,
    `**Winner: ${result.winner.optionName}** (${result.winner.confidence}% confidence)`,
    ``,
    result.winner.summary,
    ``,
    `---`,
    ``,
    `## 📊 Category Scores`,
    ``,
    `| Category | ${result.options.map(o => o.name).join(' | ')} | Weight |`,
    `| --- | ${result.options.map(() => '---').join(' | ')} | --- |`,
    ...result.categoryScores.map(c =>
      `| ${c.category} | ${result.options.map(o => `${c.scores[o.id]}/100`).join(' | ')} | ${c.weight.toFixed(1)} |`
    ),
    ``,
    `---`,
    ``,
    `## 🔮 Future Timeline`,
    ``,
    ...result.timeline.flatMap(t => [
      `### ${t.period}`,
      ...result.options.map(o => `- **${o.name}:** ${t.outcomes[o.id]}`),
      ``,
    ]),
    `---`,
    ``,
    `## ⚠️ Risk Assessment`,
    ``,
    ...result.risks.map(r =>
      `- **${r.factor}** (${r.level.toUpperCase()}): ${r.description}\n  - *Mitigation:* ${r.mitigation}`
    ),
    ``,
    `---`,
    ``,
    `## 🧠 Cognitive Bias Detection`,
    ``,
    ...result.biases.map(b =>
      `- **${b.biasType}** (${b.severity}): ${b.description}\n  - *Recommendation:* ${b.recommendation}`
    ),
    ``,
    `---`,
    ``,
    `## 😈 Devil's Advocate (Against ${result.devilsAdvocate.againstOption})`,
    ``,
    ...result.devilsAdvocate.arguments.map((a, i) => `${i + 1}. ${a}`),
    ``,
    `### Counter-Points`,
    ...result.devilsAdvocate.counterPoints.map((c, i) => `${i + 1}. ${c}`),
    ``,
    `---`,
    ``,
    `## 💡 Reasoning`,
    ``,
    `### Main Reasons`,
    ...result.reasoning.mainReasons.map(r => `- ${r}`),
    ``,
    `### Trade-offs`,
    ...result.reasoning.tradeoffs.map(r => `- ${r}`),
    ``,
    `### Hidden Costs`,
    ...result.reasoning.hiddenCosts.map(r => `- ${r}`),
    ``,
    `### Long-Term Effects`,
    ...result.reasoning.longTermEffects.map(r => `- ${r}`),
    ``,
    `---`,
    ``,
    `## Methodology`,
    ``,
    result.methodology,
    ``,
    `---`,
    ``,
    `*Report generated by INFENGINE AI Decision Intelligence Platform*`,
  ];

  return lines.join('\n');
}

function generateExecutiveSummary(result: AnalysisResult): string {
  return [
    `INFENGINE — Executive Summary`,
    `${'='.repeat(50)}`,
    ``,
    `Decision: ${result.decision}`,
    `Date: ${new Date(result.createdAt).toLocaleString()}`,
    ``,
    `RECOMMENDATION`,
    `-`.repeat(30),
    `Winner: ${result.winner.optionName}`,
    `Confidence: ${result.winner.confidence}%`,
    ``,
    result.winner.summary,
    ``,
    `KEY SCORES`,
    `-`.repeat(30),
    ...result.categoryScores.slice(0, 5).map(c =>
      `${c.category}: ${result.options.map(o => `${o.name}=${c.scores[o.id]}`).join(' vs ')}`
    ),
    ``,
    `TOP RISKS`,
    `-`.repeat(30),
    ...result.risks.filter(r => r.level === 'high' || r.level === 'critical').map(r =>
      `[${r.level.toUpperCase()}] ${r.factor}: ${r.description}`
    ),
    ``,
    `BIASES DETECTED`,
    `-`.repeat(30),
    ...result.biases.map(b => `[${b.severity.toUpperCase()}] ${b.biasType}`),
    ``,
    `NEXT STEPS`,
    `-`.repeat(30),
    result.recommendation,
  ].join('\n');
}
